import Dexie from "dexie";
import { indexedDB, IDBKeyRange } from "fake-indexeddb";
import { afterEach, expect, it } from "vitest";
import { StudyJournalDatabase } from "../../db/database";
import { DAILY_PLAN_SCHEMA_24_STORES } from "../../db/reviewCoachSchema";
import { KNOWLEDGE_SCHEMA_26_STORES } from "./schema";
import { getDefaultKnowledgeLibrary } from "./defaultLibrary";
import { KnowledgeRepository } from "./repository";
import { createKnowledgeEntity } from "./commands";
Dexie.dependencies.indexedDB = indexedDB; Dexie.dependencies.IDBKeyRange = IDBKeyRange;
const databases: Dexie[] = [];
afterEach(async () => { for (const database of databases.splice(0)) await database.delete(); });
it("MIG-09: schema26 upgrade adds local bookkeeping without rewriting existing content or starting migration", async () => {
  const name = "schema27-" + crypto.randomUUID();
  const legacy = new Dexie(name);
  legacy.version(24).stores(DAILY_PLAN_SCHEMA_24_STORES);
  legacy.version(26).stores(KNOWLEDGE_SCHEMA_26_STORES);
  await legacy.open();
  const library = { id: "local", ownerScope: "account:owner", title: "原库", cloudLibraryId: null, detached: false, restoreSessionId: null, archiveLibraryId: null };
  const command = createKnowledgeEntity("local", "workspace", "原专题");
  await legacy.table("knowledgeLibraries").put(library);
  await legacy.table("knowledgeCommands").put({ libraryId: "local", id: command.id, command, hash: "original", status: "pending", localSequence: 1 });
  await legacy.table("blocks").put({ id: "keep-log", title: "不改日志" });
  legacy.close();
  const database = new StudyJournalDatabase(name); databases.push(database); await database.open();
  expect(database.verno).toBe(27);
  expect(await database.knowledgeLibraries.get("local")).toEqual(library);
  expect((await database.knowledgeCommands.toArray())[0].command).toEqual(command);
  expect(await database.blocks.get("keep-log")).toMatchObject({ title: "不改日志" });
  expect(await database.knowledgeSyncBindings.count()).toBe(0);
  expect(await database.knowledgeLibraryMigrations.count()).toBe(0);
  database.close(); await database.open();
  expect(await database.knowledgeLibraries.count()).toBe(1);
});
it("UI-04: explicit binding wins over array order; recovery copies never become the implicit write target", async () => {
  const database = new StudyJournalDatabase("default-" + crypto.randomUUID()); databases.push(database); await database.open();
  const repository = new KnowledgeRepository(database, () => "account:owner");
  await repository.createLibrary("先排序恢复副本", "aaa", true);
  await repository.createLibrary("旧库", "bbb");
  await repository.createLibrary("同步内容", "zzz");
  await database.knowledgeLibraries.update("zzz", { cloudLibraryId: "cloud" });
  await database.knowledgeSyncBindings.put({ ownerScope: "account:owner", localLibraryId: "zzz", cloudLibraryId: "cloud", policyVersion: 1, generation: 1 });
  expect((await getDefaultKnowledgeLibrary(database, "account:owner"))?.id).toBe("zzz");
  expect(await repository.createTopic("正确位置", { id: "intent", ownerScope: "account:owner", sessionGeneration: 0 })).toMatchObject({ libraryId: "zzz" });
  await database.knowledgeLibraries.delete("zzz");
  await expect(getDefaultKnowledgeLibrary(database, "account:owner")).rejects.toMatchObject({ code: "missing" });
});
