import Dexie from "dexie";
import { indexedDB, IDBKeyRange } from "fake-indexeddb";
import { afterEach, describe, expect, it } from "vitest";
import { StudyJournalDatabase } from "../../db/database";
import { KnowledgeRepository, knowledgeTables, readKnowledgeState, writeKnowledgeStateDelta } from "./repository";
import { createKnowledgeEntity, editKnowledgeEntity } from "./commands";
import { prepareKnowledgeImport, resumeKnowledgeImport } from "./import";
import { applyKnowledgeCommand, valueOf } from "./protocol";
import { ROOT_NODE } from "./domain";
import { capturePortableKnowledge } from "./backup";

Dexie.dependencies.indexedDB = indexedDB;
Dexie.dependencies.IDBKeyRange = IDBKeyRange;
const databases: StudyJournalDatabase[] = [];
afterEach(async () => { for (const database of databases.splice(0)) await database.delete(); });
describe("knowledge explicit copy-in", () => {
  it("resumes a stable session and preserves unresolved text and move candidates without changing source", async () => {
    const database = new StudyJournalDatabase("knowledge-import-" + crypto.randomUUID());
    databases.push(database); await database.open();
    const repository = new KnowledgeRepository(database, () => "account:owner");
    await repository.createLibrary("source", "source"); await repository.createLibrary("target", "target");
    const source = await repository.open("source");
    const workspace = createKnowledgeEntity("source", "workspace", "topic");
    await repository.execute(source.context, workspace);
    const first = createKnowledgeEntity("source", "node", "first", workspace.entity.id);
    const second = createKnowledgeEntity("source", "node", "second", workspace.entity.id);
    await repository.execute(source.context, first); await repository.execute(source.context, second);
    const before = await readKnowledgeState(database, "source");
    let after = applyKnowledgeCommand(before, editKnowledgeEntity("source", before, before.entities[first.entity.id], "note", "current"));
    after = applyKnowledgeCommand(after, editKnowledgeEntity("source", before, before.entities[first.entity.id], "note", "candidate"));
    after = applyKnowledgeCommand(after, editKnowledgeEntity("source", before, before.entities[first.entity.id], "position", { parentNodeId: second.entity.id, orderKey: "V" }));
    after = applyKnowledgeCommand(after, editKnowledgeEntity("source", before, before.entities[first.entity.id], "position", { parentNodeId: ROOT_NODE, orderKey: "W" }));
    await database.transaction("rw", knowledgeTables(database), () => writeKnowledgeStateDelta(database, "source", before, after));
    const envelopeBefore = await capturePortableKnowledge(database, "account:owner");
    const target = await repository.open("target");
    await prepareKnowledgeImport(repository, "source", target.context, "session");
    const session = (await database.knowledgeImportSessions.get(["target", "session"]))!;
    const step = (await database.knowledgeImportSteps.get(["target", "session", 0]))!;
    await repository.execute(target.context, step.command, undefined, "session");
    await resumeKnowledgeImport(repository, target.context, "session");
    await resumeKnowledgeImport(repository, target.context, "session");
    await prepareKnowledgeImport(repository, "source", target.context, "session");
    const copied = (await repository.open("target")).state;
    expect(Object.keys(copied.entities)).toHaveLength(3);
    expect(Object.values(copied.candidates).filter(candidate => candidate.consumedBy === null)).toHaveLength(2);
    expect(Object.values(copied.entities).some(entity => valueOf(copied, entity, "note") === "current")).toBe(true);
    const envelopeAfter = await capturePortableKnowledge(database, "account:owner");
    expect(envelopeAfter.libraries.find(library => library.title === "source")).toEqual(envelopeBefore.libraries.find(library => library.title === "source"));
    expect((await database.knowledgeImportSessions.get(["target", "session"]))?.next).toBe(session.total);
    expect(await database.knowledgeImportSteps.count()).toBe(0);
    expect((await repository.assertContext(target.context)).sync.importSessions).toBeUndefined();
  });
});
