import Dexie from "dexie";
import { indexedDB, IDBKeyRange } from "fake-indexeddb";
import { afterEach, expect, it } from "vitest";
import { StudyJournalDatabase } from "../../db/database";
import { KnowledgeRepository, knowledgeTables, writeKnowledgeStateDelta } from "./repository";
import { createKnowledgeEntity } from "./commands";
import { applyKnowledgeCommand } from "./protocol";
import { emptyKnowledgeState } from "./domain";
import { migrateKnowledgeSources, withKnowledgeSyncLease } from "./migration";
import { knowledgeHash } from "./canonical";
Dexie.dependencies.indexedDB = indexedDB; Dexie.dependencies.IDBKeyRange = IDBKeyRange;
const databases: StudyJournalDatabase[] = [];
afterEach(async () => { for (const database of databases.splice(0)) await database.delete(); });
it.each([100, 500, 1000])("NET-06: freezes %i steps durably and resumes without growing bookkeeping or changing the tail", async count => {
  const database = new StudyJournalDatabase("bounded-adoption-" + crypto.randomUUID()); databases.push(database); await database.open();
  const repository = new KnowledgeRepository(database, () => "account:owner");
  await repository.createLibrary("来源", "source"); await repository.createLibrary("目标", "target");
  await database.knowledgeLibraries.update("target", { cloudLibraryId: "cloud" });
  let state = emptyKnowledgeState();
  for (let index = 0; index < count; index += 1) state = applyKnowledgeCommand(state, createKnowledgeEntity("source", "workspace", "专题 " + index));
  await database.transaction("rw", knowledgeTables(database), async () => {
    await writeKnowledgeStateDelta(database, "source", emptyKnowledgeState(), state);
    await database.knowledgeSyncState.update("source", { epoch: state.sequence });
  });
  const target = (await repository.open("target")).context;
  let active = true;
  const interruptAt = async (step: number) => withKnowledgeSyncLease(repository, { isCurrent: () => active }, guard => migrateKnowledgeSources(repository, target, guard, message => { if (message.includes(": " + step + " / ") || message.includes("：" + step + " / ")) active = false; }));
  await expect(interruptAt(1)).rejects.toMatchObject({ code: "cancelled" });
  const session = (await database.knowledgeImportSessions.toArray())[0];
  const migration = (await database.knowledgeLibraryMigrations.toArray())[0];
  expect(session).toMatchObject({ next: 1, total: count, status: "active" });
  expect(JSON.stringify(session).length).toBeLessThan(650);
  expect(JSON.stringify(migration).length).toBeLessThan(750);
  expect(await database.knowledgeImportSteps.count()).toBe(count - 1);
  const tailHash = knowledgeHash((await database.knowledgeImportSteps.get(["target", session.id, count - 1]))!);
  active = true;
  await expect(interruptAt(2)).rejects.toMatchObject({ code: "cancelled" });
  expect(await database.knowledgeImportSessions.get(["target", session.id])).toMatchObject({ next: 2, total: count });
  expect(await database.knowledgeCommands.where("libraryId").equals("target").count()).toBe(2);
  expect(knowledgeHash((await database.knowledgeImportSteps.get(["target", session.id, count - 1]))!)).toBe(tailHash);
}, 120000);
