import Dexie from "dexie";
import { indexedDB, IDBKeyRange } from "fake-indexeddb";
import { afterEach, expect, it, vi } from "vitest";
import { StudyJournalDatabase } from "../../db/database";
import { KnowledgeRepository, knowledgeTables, readKnowledgeState, writeKnowledgeStateDelta } from "./repository";
import { createKnowledgeEntity, editKnowledgeEntity } from "./commands";
import { applyKnowledgeCommand, validateKnowledgeState } from "./protocol";
import { ROOT_NODE } from "./domain";
import { prepareKnowledgeImport, resumeKnowledgeImport } from "./import";
import { capturePortableKnowledge } from "./backup";

Dexie.dependencies.indexedDB = indexedDB;
Dexie.dependencies.IDBKeyRange = IDBKeyRange;
const databases: StudyJournalDatabase[] = [];
afterEach(async () => { vi.unstubAllGlobals(); for (const database of databases.splice(0)) await database.delete(); });
const fixture = async () => {
  const database = new StudyJournalDatabase("review-recheck-" + crypto.randomUUID());
  databases.push(database); await database.open();
  const repository = new KnowledgeRepository(database, () => "account:a");
  await repository.createLibrary("source", "source"); await repository.createLibrary("target", "target");
  const source = await repository.open("source");
  const workspace = createKnowledgeEntity("source", "workspace", "topic");
  await repository.execute(source.context, workspace);
  return { database, repository, source, workspace };
};
it("resumes frozen import steps after source deletion and rejects a concurrent duplicate step", async () => {
  const { database, repository, source } = await fixture();
  const target = (await repository.open("target")).context;
  await prepareKnowledgeImport(repository, "source", target, "frozen");
  const step = (await database.knowledgeImportSteps.get(["target", "frozen", 0]))!;
  await repository.deleteLibrary(source.context);
  const results = await Promise.allSettled([repository.execute(target, step.command, undefined, "frozen"), repository.execute(target, step.command, undefined, "frozen")]);
  expect(results.filter(result => result.status === "fulfilled")).toHaveLength(1);
  expect(results.filter(result => result.status === "rejected")).toHaveLength(1);
  await resumeKnowledgeImport(repository, target, "frozen");
  await resumeKnowledgeImport(repository, target, "frozen");
  expect(Object.values((await repository.open("target")).state.entities)).toHaveLength(1);
  expect(await database.knowledgeImportSteps.count()).toBe(0);
  expect(await database.knowledgeImportSessions.get(["target", "frozen"])).toMatchObject({ status: "completed", next: 1, total: 1 });
});
it("preserves unresolved positions with purged targets through copy and retry", async () => {
  const { database, repository, source, workspace } = await fixture();
  const node = createKnowledgeEntity("source", "node", "node", workspace.entity.id);
  const parent = createKnowledgeEntity("source", "node", "candidate parent", workspace.entity.id);
  await repository.execute(source.context, node); await repository.execute(source.context, parent);
  const before = await readKnowledgeState(database, "source");
  let after = applyKnowledgeCommand(before, editKnowledgeEntity("source", before, before.entities[node.entity.id], "position", { parentNodeId: ROOT_NODE, orderKey: "V" }));
  after = applyKnowledgeCommand(after, editKnowledgeEntity("source", before, before.entities[node.entity.id], "position", { parentNodeId: parent.entity.id, orderKey: "W" }));
  await database.transaction("rw", knowledgeTables(database), () => writeKnowledgeStateDelta(database, "source", before, after));
  await database.knowledgeSyncState.update("source", { epoch: after.sequence });
  await repository.execute(source.context, editKnowledgeEntity("source", after, after.entities[parent.entity.id], "deleted", true));
  await repository.purgeLocalTrash(source.context);
  const purged = (await repository.open("source")).state;
  expect(() => validateKnowledgeState(purged)).not.toThrow();
  await expect(capturePortableKnowledge(database, "account:a")).resolves.toBeDefined();
  const target = (await repository.open("target")).context;
  await prepareKnowledgeImport(repository, "source", target, "purged-copy");
  await resumeKnowledgeImport(repository, target, "purged-copy");
  await resumeKnowledgeImport(repository, target, "purged-copy");
  const copied = (await repository.open("target")).state;
  const candidate = Object.values(copied.candidates).find(item => item.consumedBy === null)!;
  const position = copied.revisions[candidate.revisionId].value as { parentNodeId: string };
  expect(position.parentNodeId).toMatch(/^missing-/);
  expect(copied.entities[position.parentNodeId]).toBeUndefined();
  expect(Object.values(copied.candidates).filter(item => item.consumedBy === null)).toHaveLength(1);
  expect(() => validateKnowledgeState(copied)).not.toThrow();
  await expect(capturePortableKnowledge(database, "account:a")).resolves.toBeDefined();
});
it.each([100, 500, 1000])("keeps per-step progress and sync rows bounded with %i frozen commands", async total => {
  const { database, repository } = await fixture();
  const target = (await repository.open("target")).context;
  const commands = Array.from({ length: total }, (_, ordinal) => createKnowledgeEntity("target", "workspace", "topic-" + ordinal));
  await database.knowledgeImportSessions.put({ libraryId: "target", id: "large", sourceLibraryId: "source", sourceGeneration: 0, sourceHash: "fixed", next: 0, total, status: "active" });
  await database.knowledgeImportSteps.bulkAdd(commands.map((command, ordinal) => ({ libraryId: "target", sessionId: "large", ordinal, command })));
  const untouched = await database.knowledgeImportSteps.get(["target", "large", total - 1]);
  await repository.execute(target, commands[0], undefined, "large");
  const progress = await database.knowledgeImportSessions.get(["target", "large"]);
  expect(progress).toMatchObject({ next: 1, total });
  expect(JSON.stringify(progress).length).toBeLessThan(512);
  expect(JSON.stringify(await database.knowledgeSyncState.get("target")).length).toBeLessThan(512);
  expect(await database.knowledgeImportSteps.get(["target", "large", 0])).toBeUndefined();
  expect(await database.knowledgeImportSteps.get(["target", "large", total - 1])).toEqual(untouched);
  expect(await database.knowledgeImportSteps.count()).toBe(total - 1);
});

it("rejects stale draft deletion and permits explicit missing-recovery abandonment only after checking its hash", async () => {
  const { database, repository, source, workspace } = await fixture();
  await repository.saveDraft(source.context, { libraryId: "source", id: "draft", entityId: workspace.entity.id, unit: "note", text: "keep", expectedRevision: null, dataGeneration: 0 });
  await expect(repository.discardDraft(source.context, "draft", "other-revision")).rejects.toMatchObject({ code: "stale" });
  expect((await database.knowledgeDrafts.get(["source", "draft"]))?.text).toBe("keep");
  await database.knowledgeCommands.update(["source", workspace.id], { status: "blocked", recoveryLibraryId: "missing-copy" });
  const pending = (await database.knowledgeCommands.get(["source", workspace.id]))!;
  await expect(repository.abandonMissingRecovery(source.context, workspace.id, "wrong")).rejects.toMatchObject({ code: "stale" });
  await repository.abandonMissingRecovery(source.context, workspace.id, pending.hash);
  expect(await database.knowledgeCommands.get(["source", workspace.id])).toBeUndefined();
});
