import { formatActionableError } from "../../lib/uiError";
import { useEffect, useRef, useState } from "react";
import type { RecordBlock, RecordReviewDecisionBlockFeedbackInput } from "../../types";
import type { ReviewCoachFormalSnapshot } from "../reviewCoach/domain";
import { saveCardFeedback } from "./cardFeedback";
export function CardCoach({ record, inputs, scope, origin, snapshot, onAnalyze, onRefresh, onOpenTask, onSwitchTask, onResume, onClose }: { record: RecordBlock; inputs: RecordReviewDecisionBlockFeedbackInput[]; scope: string; origin?: { id: string; title: string }; snapshot?: ReviewCoachFormalSnapshot; onAnalyze?: (recordId: string, feedbackIds: readonly string[]) => Promise<unknown>; onRefresh: () => Promise<void>; onOpenTask?: (id: string) => void; onSwitchTask?: (id: string) => Promise<unknown>; onResume?: (id: string) => Promise<unknown>; onClose: () => void }) {
  const started = useRef(false);
  const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [submitted, setSubmitted] = useState<string[]>([]);
  const feedback = snapshot?.decisionBlockFeedback.filter(item => !item.deletedAt && item.recordId === record.id && (origin ? item.originRoundId === origin.id : !item.originRoundId)) ?? [];
  const pendingBatches = snapshot?.analysisBatches.filter(batch => !batch.deletedAt && ["confirmed", "running"].includes(batch.status) && batch.inputRefs.every(ref => ref.recordId === record.id) && batch.inputRefs.some(ref => feedback.some(item => item.id === ref.feedbackId))) ?? [];
  const tasks = snapshot?.adaptiveReviewTasks.filter(item => !item.deletedAt && item.recordId === record.id) ?? [];
  const analyze = async () => {
    if (busy) return; setBusy(true); setError("");
    try { if (pendingBatches.length && onResume) { await onResume(pendingBatches[0].id); await onRefresh(); return; } const saved = await saveCardFeedback(record, inputs, scope, origin); const ids = saved.filter(item => item.includeInAnalysis).map(item => item.id); setSubmitted(ids); await onRefresh(); if (ids.length) await onAnalyze?.(record.id, ids); }
    catch (reason) { setError(formatActionableError(reason, "ai-request")); } finally { setBusy(false); }
  };
  useEffect(() => { if (started.current) return; started.current = true; if (inputs.some(input => input.comment.trim() && input.includeInAnalysis && !feedback.some(item => item.decisionBlockId === input.decisionBlockId && item.contentVersion === input.contentVersion && item.comment === input.comment.trim() && snapshot?.feedbackInterpretations.some(result => result.feedbackId === item.id && ["succeeded", "insufficient-context"].includes(result.status))))) void analyze(); }, []);
  useEffect(() => { const handler = (event: Event) => { event.preventDefault(); event.stopImmediatePropagation(); onClose(); }; window.addEventListener("arranged-review-back", handler, true); const key = (event: KeyboardEvent) => { if (event.key === "Escape") onClose(); }; window.addEventListener("keydown", key); return () => { window.removeEventListener("arranged-review-back", handler, true); window.removeEventListener("keydown", key); }; }, [onClose]);
  return <section className="arranged-workspace card-coach-panel" aria-label="本卡学习助教"><header className="arranged-header"><button className="secondary-button" onClick={onClose}>返回卡片</button><h1>学习助教</h1></header><h2>{record.title}</h2><button className="primary-button" disabled={busy || !onAnalyze || (!pendingBatches.length && !inputs.some(item => item.comment.trim() && item.includeInAnalysis))} onClick={() => void analyze()}>{busy ? "正在分析…" : pendingBatches.length ? "继续本卡分析" : error ? "重试分析" : "分析本卡"}</button>{busy && <p role="status">正在处理本卡反馈</p>}{error && <p role="alert">{error}</p>}
    {feedback.filter(item => !submitted.length || submitted.includes(item.id)).map(item => { const interpretation = snapshot?.feedbackInterpretations.find(value => value.feedbackId === item.id && !value.deletedAt); const queue = snapshot?.analysisQueueItems.find(value => value.feedbackId === item.id); return <article className="card-coach-result" key={item.id}><strong>{item.comment}</strong><p>{interpretation?.stuckAt || (interpretation?.status === "succeeded" ? "反馈已分析" : interpretation?.status === "failed" ? "分析失败，可重试" : "待分析")}</p>{interpretation?.preferredPractice && <p>{({ "variation": "变式练习", "concept-question": "概念理解", "calculation": "计算练习", "distinction": "辨析练习", "cloze": "填空练习", "chunk-training": "分步练习", "prerequisite-check": "前置知识检查" } as Record<string, string>)[interpretation.preferredPractice] ?? interpretation.preferredPractice}</p>}{interpretation?.missingInformation?.length ? <p>{interpretation.missingInformation.join("；")}</p> : null}{item.includeInAnalysis && queue?.status === "eligible" && <button className="secondary-button" disabled={busy || !onAnalyze} onClick={() => { setBusy(true); setError(""); setSubmitted([item.id]); void onAnalyze?.(record.id, [item.id]).catch(reason => setError(formatActionableError(reason, "ai-request"))).finally(() => setBusy(false)); }}>分析这条反馈</button>}{queue?.status === "eligible" && tasks.some(task => task.decisionBlockId === item.decisionBlockId && ["waiting", "current", "in-progress", "deferred"].includes(task.status)) && <small>已有训练任务，新反馈保留待后续分析</small>}</article>; })}
    {tasks.map(task => { const blueprint = snapshot?.sessionBlueprints.find(item => item.id === task.blueprintId); return <article className="card-coach-result" key={task.id}><strong>{blueprint?.objective ?? "本卡训练"}</strong><p>{blueprint?.problemHypothesis}</p><button className="secondary-button" onClick={() => { void (async () => { try { if (!["current", "in-progress"].includes(task.status)) await onSwitchTask?.(task.id); onOpenTask?.(task.id); } catch (reason) { setError(formatActionableError(reason, "adaptive-review")); } })(); }} disabled={!onOpenTask || ["completed", "abandoned", "stale", "invalid"].includes(task.status)}>{task.status === "completed" ? "已完成" : "进入训练"}</button></article>; })}
  </section>;
}
